# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true  # default
contact_links:
- name: ğŸ‘©ğŸ½â€ğŸ’» main napari repository
  url: https://github.com/napari/napari
  about: |
    If your issue requires a docstring update, or changes to the examples gallery, please check the main napari repo.
- name: âœ¨ napari-sphinx-theme
  url: https://github.com/napari/napari-sphinx-theme
  about: |
    If your issue is about the napari.org website design or functionality, please check the napari-sphinx-theme repo.
- name: ğŸ¤·ğŸ’» napari forum
  url: https://forum.image.sc/tag/napari
  about: |
    Please ask general "how do I ... ?" questions over at image.sc
- name: 'ğŸ’¬ napari @ zulip'
  url: https://napari.zulipchat.com/
  about: Chat with devs
